<a href="https://colab.research.google.com/github/willow788/one-model-a-week-keeps-the-fomo-away/blob/main/ocr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install opencv-python

In [3]:
#importing the assets
import numpy as np
import cv2


In [4]:
#reading the img
image = cv2.imread('/content/digits1.png')

In [5]:
#converting the img to grayscale
gray_img = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [6]:
#dividing the img into 5000 small dimensions each of 20 x  20 pixels
divisioned_img = list(np.hsplit(i, 100)
for i in np.vsplit(gray_img, 50))


In [8]:
from os import NGROUPS_MAX
#converting to numpy array
np_array= np.array(divisioned_img)
print(np_array)

[[[[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  ...

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  1  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]]

  [[ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0  0]
   ...
   [ 0  0  0 ...  0  0  0]
   [ 0  0  0 ...  0  0 

In [10]:
#prepping the training and testing data
train_data = np_array[:, :50].reshape(-1, 400).astype(np.float32)
testing_data = np_array[:,50:100].reshape(-1,400).astype(np.float32)


In [11]:
#creating labels
k = np.arange(10)
train_labels = np.repeat(k, 250)[:, np.newaxis]
test_labels = np.repeat(k, 250)[:, np.newaxis]


In [13]:
#initiate knn algo
knn = cv2.ml.KNearest_create()

#TRAINING
knn.train(train_data,
          cv2.ml.ROW_SAMPLE,
          train_labels
          )

True

In [15]:
ret, output, neighbour, distance = knn.findNearest(testing_data, 3)
print(output)
print(neighbour)
print(distance)

[[0.]
 [0.]
 [0.]
 ...
 [9.]
 [9.]
 [9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [9. 9. 9.]
 [9. 9. 7.]
 [9. 9. 9.]]
[[ 361955.  598018.  606136.]
 [ 790595.  959768. 1055851.]
 [ 534520.  641045.  681043.]
 ...
 [ 632329.  646093.  712409.]
 [ 464467.  784272.  872704.]
 [1315263. 1358024. 1463505.]]


In [17]:
matched = output==test_labels
correct_op = np.count_nonzero(matched)
print(matched)

[[ True]
 [ True]
 [ True]
 ...
 [ True]
 [ True]
 [ True]]


In [18]:
#accuracy
acc = (correct_op * 100.0)/(output.size)
print(acc)

91.64
